### ISSUE TITLE
2.0.0 출시 전 수정사항

### ISSUE THREAD

**Issue by honghoker** [honghoker/hongkimDaonProject#44]
## 🛠 Issue
2.0.0 출시 전 수정사항입니다.

## 📝 To-do

- [ ] Tuist 모듈화
- [ ] MVC -> CleanArchitecture + MVVM + Rxswift
- [ ] Realm -> GRDB
- [ ] Skeleton 적용(tableView)
- [ ] Test 코드 작성
- [ ] Xcode Cloud 배포 자동화
- [ ] API 요청 시 발생하는 네트워크 연결, 서버 응답 에러 예외처리(Toast)

## 추후
- [ ] DI - Needle로 변경하여 리팩토링
